name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-83-113-237.compute-1.amazonaws.com << 'EOF'
          cd /home/ubuntu/YAWN-FRONTEND
          echo "${{ secrets.ENV_CONTENT }}" > .env
          git pull origin main
          npm install --legacy-peer-deps
          npm run build
          sudo systemctl restart nginx
          EOF
